# Generated by Django 5.2.3 on 2025-06-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_description'),
        ('users', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user_id', 'recipe_id')},
        ),
    ]
