# Generated by Django 5.2.3 on 2025-06-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_parent_category_id_category_parent_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit_type_id',
            new_name='unit_type',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
