# Generated by Django 5.2.1 on 2025-06-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_recipe_id_step_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category_id',
            new_name='parent_category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
    ]
