# Generated by Django 5.2.1 on 2025-06-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_parent_category_id_category_parent_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent_category_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='user_id',
        ),
    ]
